#!/bin/bash

if [[ $1 =~ ^[0-9]*$ ]]; then
  if [ -d /sys/fs/cgroup/cpu/lxc/$1 ]; then
    CONTAINER=$1
    shift
    COMMAND=$@
    echo -ne "$(tput setaf 10)executing \"$COMMAND\" in container #${CONTAINER} ($(grep -m 1 hostname /etc/pve/lxc/${CONTAINER}.conf | awk '{print $NF}'))$(tput sgr0)\n"
    exec > >(trap "" INT TERM; sed "s/^/$(tput setaf 14)$CONTAINER | $(tput sgr0)/")
    exec 2> >(trap "" INT TERM; sed "s/^/$(tput setaf 1)$CONTAINER | $(tput setaf 9)/" >&2)
    pct exec $CONTAINER /bin/bash -- -c "$COMMAND"
  else
    echo -ne "$(tput setaf 10)container $1 is not running$(tput sgr0)\n"
    exit 1
  fi
fi
